version: 0.2

phases:
  install:
    commands:
      - npm install
  test:
    commands:
      - npm test
  build:
    commands:
      - npm run build

artifacts:
  files:
     - '**/*'
  base-directory: build
